
//  Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//  http://www.mikroe.com 
//  RBO 2016

//  FontName : small3x5
//  FontSize : 3 x 5
//  Digits are OK
//  Some characters are impossible to draw properly in 3x5 grid e.g. m, w, /, \, etc.

static const unsigned char Terminal3x5[96][3] = {
        {0x00, 0x00, 0x00},                        // Code for char  
        {0x00, 0x17, 0x00},                        // Code for char !
        {0x03, 0x00, 0x03},                        // Code for char "
        {0x1F, 0x0A, 0x1F},                        // Code for char #
        {0x17, 0x15, 0x1D},                        // Code for char $
        {0x0A, 0x15, 0x0A},                        // Code for char %
        {0x04, 0x0E, 0x04},                        // Code for char &
        {0x03, 0x00, 0x00},                        // Code for char '
        {0x0E, 0x11, 0x00},                        // Code for char (
        {0x00, 0x11, 0x0E},                        // Code for char )
        {0x05, 0x02, 0x05},                        // Code for char *
        {0x04, 0x0E, 0x04},                        // Code for char +
        {0x10, 0x08, 0x00},                        // Code for char ,
        {0x04, 0x04, 0x04},                        // Code for char -
        {0x00, 0x10, 0x00},                        // Code for char .
        {0x18, 0x04, 0x03},                        // Code for char /
        {0x1F, 0x11, 0x1F},                        // Code for char 0
        {0x00, 0x1F, 0x00},                        // Code for char 1
        {0x1D, 0x15, 0x17},                        // Code for char 2
        {0x15, 0x15, 0x1F},                        // Code for char 3
        {0x07, 0x04, 0x1F},                        // Code for char 4
        {0x17, 0x15, 0x1D},                        // Code for char 5
        {0x1F, 0x15, 0x1D},                        // Code for char 6
        {0x01, 0x01, 0x1F},                        // Code for char 7
        {0x1F, 0x15, 0x1F},                        // Code for char 8
        {0x07, 0x05, 0x1F},                        // Code for char 9
        {0x00, 0x0A, 0x00},                        // Code for char :
        {0x10, 0x0A, 0x00},                        // Code for char ;
        {0x04, 0x0A, 0x11},                        // Code for char <
        {0x0A, 0x0A, 0x0A},                        // Code for char =
        {0x11, 0x0A, 0x04},                        // Code for char >
        {0x01, 0x15, 0x03},                        // Code for char ?
        {0x0F, 0x09, 0x1F},                        // Code for char @
        {0x1F, 0x05, 0x1F},                        // Code for char A
        {0x1F, 0x15, 0x1B},                        // Code for char B
        {0x1F, 0x11, 0x11},                        // Code for char C
        {0x1C, 0x14, 0x1F},                        // Code for char D
        {0x1F, 0x15, 0x11},                        // Code for char E
        {0x1F, 0x05, 0x01},                        // Code for char F
        {0x1F, 0x11, 0x19},                        // Code for char G
        {0x1F, 0x04, 0x1F},                        // Code for char H
        {0x11, 0x1F, 0x11},                        // Code for char I
        {0x11, 0x1F, 0x01},                        // Code for char J
        {0x1F, 0x04, 0x1B},                        // Code for char K
        {0x1F, 0x10, 0x10},                        // Code for char L
        {0x1F, 0x06, 0x1F},                        // Code for char M
        {0x1F, 0x01, 0x1E},                        // Code for char N
        {0x1F, 0x11, 0x1F},                        // Code for char O
        {0x1F, 0x05, 0x07},                        // Code for char P
        {0x0F, 0x09, 0x1F},                        // Code for char Q
        {0x1F, 0x05, 0x1B},                        // Code for char R
        {0x17, 0x15, 0x1D},                        // Code for char S
        {0x01, 0x1F, 0x01},                        // Code for char T
        {0x1F, 0x10, 0x1F},                        // Code for char U
        {0x0F, 0x10, 0x0F},                        // Code for char V
        {0x1F, 0x0C, 0x1F},                        // Code for char W
        {0x1B, 0x04, 0x1B},                        // Code for char X
        {0x17, 0x14, 0x1F},                        // Code for char Y
        {0x19, 0x15, 0x13},                        // Code for char {
        {0x1F, 0x11, 0x00},                        // Code for char [
        {0x03, 0x04, 0x18},                        // Code for char BackSlash
        {0x00, 0x11, 0x1F},                        // Code for char ]
        {0x02, 0x01, 0x02},                        // Code for char ^
        {0x10, 0x10, 0x10},                        // Code for char _
        {0x03, 0x00, 0x00},                        // Code for char `
        {0x0C, 0x0A, 0x1E},                        // Code for char a
        {0x1F, 0x14, 0x1C},                        // Code for char b
        {0x1C, 0x14, 0x14},                        // Code for char c
        {0x1C, 0x14, 0x1F},                        // Code for char d
        {0x1F, 0x15, 0x17},                        // Code for char e
        {0x1F, 0x05, 0x00},                        // Code for char f
        {0x17, 0x15, 0x1F},                        // Code for char g
        {0x1F, 0x04, 0x1C},                        // Code for char h
        {0x00, 0x1D, 0x00},                        // Code for char i
        {0x10, 0x1D, 0x00},                        // Code for char j
        {0x1F, 0x04, 0x1A},                        // Code for char k
        {0x00, 0x1F, 0x00},                        // Code for char l
        {0x1E, 0x0C, 0x1E},                        // Code for char m
        {0x1E, 0x02, 0x1C},                        // Code for char n
        {0x1C, 0x14, 0x1C},                        // Code for char o
        {0x1F, 0x05, 0x07},                        // Code for char p
        {0x07, 0x05, 0x1F},                        // Code for char q
        {0x18, 0x04, 0x04},                        // Code for char r
        {0x17, 0x15, 0x1D},                        // Code for char s
        {0x1E, 0x14, 0x00},                        // Code for char t
        {0x0C, 0x10, 0x1C},                        // Code for char u
        {0x0C, 0x10, 0x0C},                        // Code for char v
        {0x1C, 0x18, 0x1C},                        // Code for char w
        {0x14, 0x08, 0x14},                        // Code for char x
        {0x17, 0x14, 0x1F},                        // Code for char y
        {0x1A, 0x1A, 0x16},                        // Code for char {
        {0x04, 0x1F, 0x11},                        // Code for char {
        {0x00, 0x1F, 0x00},                        // Code for char |
        {0x11, 0x1F, 0x04},                        // Code for char }
        {0x0C, 0x04, 0x06},                        // Code for char ~
        {0x00, 0x00, 0x00}                        // Code for char 
 };

